site_name: SmartLock Design Reference
site_dir: smart_lock_server
nav:
        - Introduction:
            - SmartLock Design Reference: index.md
            - Project Description: project-description.md
            - Hardware & Software requirements: hw-sw-requirements.md
        - SmartLock on AMD Kria&trade; KV260:
            - Initial setup configuration: boards/amd-kria-kv260/initial-setup-configuration.md
            - Run the code: boards/amd-kria-kv260/run-smartlock.md
#        - Testbenches:
#            - AMD Kria&trade; KV260: boards/amd-kria-kv260/testbench.md

theme: readthedocs
extra:
  version: v3.1.1
